### ISSUE TITLE
Basic build instructions on Ubuntu

### ISSUE THREAD

**Issue by tostercx** [mgwilliams/python3-pjsip#1]
Took me a while to figure this out so someone might find it useful.

Follow https://trac.pjsip.org/repos/wiki/Getting-Started/Autoconf and build pjsip with the shared library option enabled:

```
sudo apt-get install libasound2-dev
./configure --enable-shared
make dep
make
sudo make install
```

After building clone this repo into ```pjproject-2.x.x/pjsip-apps/src/python3-pjsip```
Go to the directory, build, install:

```
sudo apt-get install python3-dev
python3 setup.py build
sudo python3 setup.py install
```

Finally test if it's importing correctly:

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pjsua
>>>
```

If it complains about being unable to find a .so file, add ```/usr/local/lib``` to ldconfig: https://unix.stackexchange.com/a/67784/120790

**Comment by blaine12100** [comment]
Hi

I tried the build arguments and they work for python 3.7. I am actually using pipenv with my project so is there a way to run this in a virtual environment?

**Comment by blaine12100** [comment]
> Hi
> 
> I tried the build arguments and they work for python 3.7. I am actually using pipenv with my project so is there a way to run this in a virtual environment?

I actually did this by activating the shell environment in the same directory and running the same commands so that it writes the pjsua package in the virtualenv folder.

**Comment by IishaWu** [comment]
hello, my name is Nicole. I'm a  student. I finished compiling the pjproject-2.9. However, when I execute setup.py, it's will show an error.
_pjsua.h:26:10: fatal error: Python.h: No such file or directory
 #include <Python.h> 

Do you know how to solve this?

**Comment by IishaWu** [comment]
I solve the problem by copy all files in /usr/bin/python3.7 to pjproject-2.9/pjsip/lib and copy /usr/include/python3.7 to pjproject-2.9/pjsip/include.
However, when I do "import pjsua", it will show an error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicole/Research/pjproject-2.9/pjsip-apps/src/python3-pjsip/pjsua.py", line 60, in <module>
    import _pjsua
ImportError: libpjsua.so.2: cannot open shared object file: No such file or directory

**Comment by tostercx** [comment]
If you're on Ubuntu, try running `ldconfig /usr/local/lib` before python - that's where the so file should be installed to.

**Comment by mgwilliams** [comment]
You also need to ensure you have python3.7-dev package installed (which is
what provides Python.h).

**Comment by IishaWu** [comment]
Thank you very much! I forget to install python3.7-dev.
The following is all steps I need.(In python3.7 virtual enviroment and ubuntu18.04).
$ apt-get install python3.7 python3.7-dev
$ virtualenv -p /usr/bin/python3.7 pjsip_python3.7
$ source pjsip_python3.7/bin/activate
$ wget https://www.pjsip.org/release/2.9/pjproject-2.9.tar.bz2
$ tar -xf pjproject-2.9.tar.bz2 && cd pjproject-2.9/
$  ./configure --enable-shared
$  make dep
$  make
$  make install
$  sudo make install
$  cd pjsip-apps/src
$  git clone https://github.com/mgwilliams/python3-pjsip.git
$  cd python3-pjsip/
$ python setup.py install
$ export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
# try 
$ python
>>> import pjsua

**Comment by IishaWu** [comment]
Hello, I try to compile pjsip on windows10 by visual studio 2017.
According to the [pjsip.org](https://trac.pjsip.org/repos/wiki/Python_SIP/Build_Install), I add C:/Python24/include and C:/Python24/libs in python_pjsua property vcc++ dictionary. Then, I need to build the python_pjsua.
However,  it will show an error.
LNK1104: cannot open file 'python24_d.lib'

**Comment by mgwilliams** [comment]
Closing this issue, as I believe #2 covers basic build instructions now.

**Comment by addyuchiha** [comment]
hello i am addy can you help me with this error

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pjsua.py", line 60, in <module>
    import _pjsua
ImportError: libpjsua.so.2: cannot open shared object file: No such file or directory`
