### ISSUE TITLE
Error: Installing using Build command 

### ISSUE THREAD

**Issue by silicon-ninja** [mgwilliams/python3-pjsip#11]
### I did run the command
```bash
python3 setup.py build 
```
and this error came in, 
![Screenshot from 2021-12-15 10-53-15](https://user-images.githubusercontent.com/48326585/146128553-ceeaab38-2cea-4f09-8314-ecf885591eb4.png)

### re-installed pjsua and configured it now it says this. 

![Screenshot from 2021-12-15 11-01-51](https://user-images.githubusercontent.com/48326585/146129181-7aea2f33-540a-41db-86c8-71689ee8f9e6.png)

**Comment by TamojitSaha** [comment]
I faced the same issue today.
Solved it by running: 
```bash 
export CFLAGS="-fPIC"
```
and again recompiling after
```bash
sudo make clean  && make dep && make
```

For reference I have written detailed guide [here](https://github.com/TamojitSaha/python3-pjsip/wiki/Instruction-for-compiling-PJSUA-in-Ubuntu-18.04-and-22.04)

Let me know if it solves the issue.

**Comment by marcogaruthix** [comment]
> I faced the same issue today. Solved it by running:
> 
> ```shell
> export CFLAGS="-fPIC"
> ```
> 
> and again recompiling after
> 
> ```shell
> sudo make clean  && make dep && make
> ```
> 
> For reference I have written detailed guide [here](https://github.com/TamojitSaha/python3-pjsip/wiki/Instruction-for-compiling-PJSUA-and-PJSUA2-in-Ubuntu-18.04)
> 
> Let me know if it solves the issue.

Thanks for you colaboration, the guide is complete and worked for me

**Comment by TamojitSaha** [comment]
@marcogaruthix  Glad I could help you.

**Comment by addyuchiha** [comment]
hello i am addy can you help me with this error

Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.10/dist-packages/pjsua.py", line 60, in <module> import _pjsua ImportError: libpjsua.so.2: cannot open shared object file: No such file or directory
