### ISSUE TITLE
import pjsua

### ISSUE THREAD

**Issue by addyuchiha** [mgwilliams/python3-pjsip#14]
why is this happening?
```

>>> import pjsua
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pjsua.py", line 60, in <module>
    import _pjsua
ImportError: libpjsua.so.2: cannot open shared object file: No such file or directory
```

**Comment by BlackDeath-Pete** [comment]
I got the same error and the Comment section in the readme file was the solution:
> If when you import the package the compiler complains about the lack of some .so file, add the /usr/local/lib directory to ldconfig - [Explanation](https://unix.stackexchange.com/a/67784/120790).

**Comment by addyuchiha** [comment]
I just redownloded it and it got fixed
